# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f3001d003e54395b4cdcaad611df1ef3e64bd8c8d8d966b83e4e0ac125f9e3026325da4488156236884e40c8ef23e1d8f5ec40d152275c1e656e00f4f8577da

test:
  secret_key_base: 793a25b6453fa8fe130a4359d12cf3f1c9f5dcff8e8b73d7a3bf51513751c9dcaac12785b57f1186bdc3731bc78c7d9fa96185e0128c061a2e1aec54da51d0f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
